### ISSUE TITLE
Maximize problem in fedora 27

### ISSUE THREAD

**Issue by deepaklorkhatri007** [GNUSim8085/GNUSim8085#24]
I am not able to get maximize button when trying to install it from Fedora repositories. When I make it from source code it gives a maximize button which actually is of no use also I am not able to resize the gnusim8085 application window in Fedora 27, due to which bottom part of the application is not accessible to the user.

**Comment by onkarshinde** [comment]
@deepaklorkhatri007 I installed the application from Fedora repositories and I can see the maximize buttons. I am using LXDE.
I think your issue for maximise button depends on the window manager.

As for the window size, please confirm if you are compiling from git. I can suggest a code change which should solve the problem. Once you confirm I will commit the fix to git.

**Comment by onkarshinde** [comment]
Following function call is present three times in src/interface.c
gtk_window_set_default_size

Can you comment this, rebuild the application and check if that solves the resize problem?

**Comment by deepaklorkhatri007** [comment]
I switched from gnome to KDE and it works fine there. I tried it with other operating systems running gnome and problem is still persistent thank you!

**Comment by onkarshinde** [comment]
Did you try the code change I suggested?

**Comment by deepaklorkhatri007** [comment]
Yes that bring back the maximize button (sometimes) but i can't resize the
window still. This same issue is with gimp and krita and i found out that
if the no. Of docks in the presently opened window increase by a limit this
happens. I think this may help you debug the problem.

**Comment by onkarshinde** [comment]
I am not sure what you mean by no of docks in presently opened window. Since I am not able to reproduce the issue in either Ubuntu or Fedora I am not sure how much I can help.

The application requires very less screen space in un-maximised state. So it is a surprise to me that some of the part of the application is going out of screen.

**Comment by deepaklorkhatri007** [comment]
Okay ill send you a video of the problem then. In my knowledge Ubuntu uses
unity desktop and you are not using gnome in fedora as well so try to
install it in gnome environment i hope you'll definitely see the problem
there.

**Comment by deepaklorkhatri007** [comment]
Well, I somehow solved this problem it only needs some font size tweaking, I am very thankful for your precious time. here is a small video of the solution https://youtu.be/15YpOuWrOn0.
